name: Update Spotify Widget

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install spotify-web-api-node@^5.0.0

      - name: Fetch currently playing song
        run: node fetch-spotify.js

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Spotify widget"
          git push
